// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "2cb31add-98e7-4bfa-9d49-e5b30fd47ac9");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1765126176);
user_pref("app.update.lastUpdateTime.background-update-timer", 1765126176);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1765126176);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1765126176);
user_pref("app.update.lastUpdateTime.region-update-timer", 1765126176);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1765126146);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1765126176);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1765126176);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{c7ceb4ef-02f4-411b-a7e2-3d1cbc06eeb2}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1765126144);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 155);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2029b1e2-30d7-46f0-bb97-522edc0ff0e0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1765126145);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1765126148369");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1765147748369");
user_pref("browser.search.region", "PE");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20251106203603");
user_pref("browser.startup.homepage_override.mstone", "140.5.0");
user_pref("browser.startup.lastColdStartupCheck", 1765126146);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1765126146);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":22,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("captchadetection.lastSubmission", 1765126);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "6d9799b5-ecfb-4a45-a9eb-5fec27b965a3");
user_pref("datareporting.dau.cachedUsageProfileID", "c39b7cb5-ddfa-4db1-a9f9-db8b88424804");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1765126145525");
user_pref("distribution.iniFile.exists.appversion", "140.5.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "PE");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "ea7cf17be18a4e9db8287c3f349b4670");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECNVLvHZm2aGOBAjqtcYxfDm9Rw==");
user_pref("extensions.getAddons.cache.lastUpdate", 1765126177);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20251106203603");
user_pref("extensions.lastAppVersion", "140.5.0");
user_pref("extensions.lastPlatformVersion", "140.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"aaa69cd1-d284-49a1-839e-8feb15442cf0\",\"newtab@mozilla.org\":\"2232bd83-894d-4816-8bec-f9e803ffc968\",\"pictureinpicture@mozilla.org\":\"b1444355-464e-4601-bcd3-18cfc0b662cd\",\"addons-search-detection@mozilla.com\":\"0826dba9-5350-4f59-8938-6f2f4dbf162c\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"default-theme@mozilla.org\":\"b58a5aa5-12a5-443f-ba15-27cbc9891ebd\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "f5246bf14d038adf4ce0c4360262ab722bc3de4220f047c3d542b4c564074b4877dc8659e3125c5171c749e7ce93f20cc63777eb5e1539e960670cbc5f30ac85");
user_pref("media.gmp-gmpopenh264.lastDownload", 1765126177);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1765126177);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1765126177);
user_pref("media.gmp-gmpopenh264.version", "2.6.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 1);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "3b9c3372-1461-45d6-82cb-6b994e221b37");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.settings.clock_skew_seconds", -1427);
user_pref("services.settings.last_update_seconds", 1765127603);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECA8r11+ezcvDBAgRGBXtnx9vHw==");
user_pref("toolkit.profiles.storeID", "9cfbe6e1");
user_pref("toolkit.startup.last_success", 1765126143);
user_pref("toolkit.telemetry.cachedClientID", "d0b21dbe-2822-4345-a54c-45b2bf820438");
user_pref("toolkit.telemetry.cachedProfileGroupID", "8c444b2c-d0d1-408e-8c6a-6b1801e76277");
user_pref("toolkit.telemetry.previousBuildID", "20251106203603");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
